[package]
name = "solana_native_program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = { version = "1.5.6", features = ["derive"] }
borsh-derive = "1.5.6"
solana-program = "2.2.1"
